### ISSUE TITLE
Possible race issue?

### ISSUE THREAD

**Issue by mindreader** [ocharles/pipes-postgresql-simple#7]
There is a race condition with worker <- Async.async $ do ... followed by liftIO $ Async.link worker where if an exception is thrown before the link function takes effect, the exception will be thrown that you can't block with pipes and ended up having to add an mvar to prevent problems down the line.  This could happen in your library if you say, run a bad query and it returns really quickly.

I haven't actually experienced this with pipes-postgresql-simple, but I wrote a mysql version of it modeled after your code and ran into this problem.  Figured you might like to know.  This was how I fixed it.

```
query :: (MonadIO m, QueryResults r, QueryParams params) => My.Connection -> My.Query -> params -> Pipes.Producer' r m ()
query c q p = do
    (o, i, seal) <- liftIO (Pipes.spawn' Pipes.Single)
    mvar <- liftIO $ newEmptyMVar
    worker <- liftIO $ Async.async $ do
        takeMVar mvar
        My.fold c q p () (const $ void . STM.atomically . Pipes.send o)
        STM.atomically seal
    liftIO $ Async.link worker
    liftIO $ putMVar mvar ()
    Pipes.fromInput i
```

If this is totally inapplicable to your library due to some internal logic in postgresql-simple, then by all means close this, but I don't think I see anything that would prevent it.

**Comment by ocharles** [comment]
This library is now deprecated in favor of http://hackage.haskell.org/package/streaming-postgresql-simple. If you still have concerns about the reliability of `pipes-postgresql-simple`, please check out `streaming-postgresql-simple` and see if it has the same problems. Thanks!

**Comment by mindreader** [comment]
Roger.
